### ISSUE TITLE
Fortress clarification

### ISSUE THREAD

**Issue by charlierudolph** [dylan/gameofcyvasse#10]
I like the idea of making it destructible, but I believe that behavior needs to be clarified.

If you attack it with a ranged unit, the fortress is simply destroyed. 

But if you attack it with a normal unit (that captures by melee) where is the attacking piece placed (if a piece in the fortress it cannot move into the fortress)? 

Maybe its placed on the last space on its path to the fortress?

I also think you should limit what pieces can destroy a fortress. A rabble destroying a fortress doesn't make much sense.

**Comment by jf1x** [comment]
In my mind, a melee piece will first need to approach the fortress. This would use (using a Light Horse as an example) 1-2 of its 3 possible movements. Now that it is adjacent to the fortress, the final move would be an attack on the fortress, destroying it (if it held a unit it was allowed to attack).

I may be incorrect in the assumption of taking each movement step 1 at a time, but if this is the case, the problem you've brought up doesn't matter too much. If however, all movements must be made in a straight line at the same time, then landing on the last space before the fortress would work too.

I assume rabbles can only destroy fortresses that are holding a piece they are able to attack (opposing rabble, spearman, or king, if I remember correctly). If you want to defend your fortress more heavily, a higher ranking unit should be stationed there.

**Comment by dylan** [comment]
> I also think you should limit what pieces can destroy a fortress. A rabble destroying a fortress doesn't make much sense.

When considering this rule I kept in mind the following: We know that fortresses can be 'ruined' (based on the book), and I tried to make sure the rules were always as simple as possible (thinking along the lines of chess complexity, just different behaviors/more variety). So I tried to make a tile that can act as: force projection (allow a crossbowman/trebuchet to dally in the front longer than normal), defensive point (allow a lower unit to hold a pass against greater forces), and as a salvation (say a cornered king in it's final moves having to be attacked twice instead of once). 

> If you attack it with a ranged unit, the fortress is simply destroyed.
> 
> But if you attack it with a normal unit (that captures by melee) where is the attacking piece placed (if a piece in the fortress it cannot move into the fortress)?

If you think in terms of sieges, yes it is odd that say, a crossbowman can take out a fortress. But if you think in terms of a couple dozen guys chasing another into a fortress, it would be easy for a small band to infiltrate it. So as far as tactics go I'm not sure what opinion I have. I will however say that just adding a clause preventing or only allowing certain units to ruin a fort would complicate the rules and leave them inelegant.

> Maybe its placed on the last space on its path to the fortress?

It does make sense to leave the piece that just ruined the fortress via melee adjacent to the fortress tile, and it should be mentioned. This would mean that melee attempts on a fortress can incur great cost and you should assemble a force to pry a unit out of it's location.

> I assume rabbles can only destroy fortresses that are holding a piece they are able to attack (opposing rabble, spearman, or king, if I remember correctly). If you want to defend your fortress more heavily, a higher ranking unit should be stationed there.

It also makes sense that a unit cannot assault a fortress if it cannot typically attack the unit occupying it.

**Comment by charlierudolph** [comment]
Good points. You've clarified my questions. 

Brought up a couple more though. Can you attack an empty fortress? Range attacks seem fine but for melee units I assume they would simply walk into the fortress instead of destroying it.

**Comment by dylan** [comment]
> Brought up a couple more though. Can you attack an empty fortress? Range attacks seem fine but for melee units I assume they would simply walk into the fortress instead of destroying it.

I would say that anyone can occupy an unoccupied fortress, it's only owned by whoever is in it. :D

**Comment by dylan** [comment]
See https://github.com/dylan/gameofcyvasse/commit/dec026e3bb7ba8a5174d43d7bde70c60e33cb6f3 for changes.
